[package]
name = "komi_lexer"
version = "0.0.0-local"
publish = false
edition = "2024"

[dependencies]
komi_util = { path = "../komi_util" }
komi_syntax = { path = "../komi_syntax" }

[dev-dependencies]
rstest = "0.25.0"