#!/usr/bin/env bash
# pre-commit: pre commit hook for git

# block commit if codes not formatted
cargo fmt --check
if [ $? -ne 0 ]; then
  echo ""
  echo "Info: pre-commit hook blocked your commit."
  echo "Info: Rust code is not properly formatted. run 'cargo fmt' to fix."
  exit 1
fi