name: cd

# usage: set secrets.PACKAGES_TOKEN as github token with write:packages permission to publish package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  cd:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.86.0
          override: true
          rustflags: ""
      - run: rustc --version
      - run: cargo install wasm-pack@0.13.1

      - name: run cd script
        run: ./bin/cd
        env:
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }} # sometimes secrets.GITHUB_TOKEN doesn't work so use manually created token