name: cd

# usage: set secrets.PACKAGES_TOKEN as github token with write:packages permission to publish package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  cd:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.15.1

      - name: run cd script
        run: ./bin/cd
        env:
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }} # sometimes secrets.GITHUB_TOKEN doesn't work so use manually created token