name: ci

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.86.0
          components: rustfmt
          override: true
          rustflags: ""
      - run: rustc --version

      - name: cache cargo bin
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-bin-${{ runner.os }}-wasm

      - name: install wasm-pack
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install wasm-pack@0.13.1

      - name: run ci script
        run: ./bin/ci